version: '3.3'
services:
  db:
    container_name: db
    image: mariadb:10.11.3
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mariadb/data

  website:
    image: php:8.0.3-apache
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ENV_VERSION: ${ENV_VERSION}
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      FORBIDDEN_NAMES: ${FORBIDDEN_NAMES}
      G_AUTH_ID: ${G_AUTH_ID}
      G_AUTH_SECRET: ${G_AUTH_SECRET}
      MAIL_ACCOUNT: ${MAIL_ACCOUNT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80

  composer:
    restart: "no"
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
      - ./composer.json:/app/composer.json
    working_dir: /app
    environment:
    - COMPOSER_PROCESS_TIMEOUT=2000
    command: install

volumes:
  db:
  