version: '3.3'
services:
  db-staging:
    container_name: db-staging
    image: mariadb:10.11.3
    restart: always
    command: [ "--max_connections=1000" ]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3300:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./config:/etc/mysql/conf.d/my.cnf
      - db-staging:/var/lib/mariadb/data

  website-staging:
    image: php:8.0.3-apache
    container_name: website-staging
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db-staging
    volumes:
      - .:/var/www/html/
    environment:
      DB_HOST: db-staging
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ENV_VERSION: ${ENV_VERSION}
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      FORBIDDEN_NAMES: ${FORBIDDEN_NAMES}
      MAIL_ACCOUNT: ${MAIL_ACCOUNT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 4200:80

  phpmyadmin-staging:
    image: phpmyadmin:latest
    container_name: phpmyadmin-staging
    links:
      - db-staging
    environment:
      PMA_HOST: db-staging
    restart: always
    ports:
      - 4201:80

  composer-staging:
    restart: "no"
    image: composer:latest
    container_name: composer-staging
    volumes:
      - .:/app
      - ./composer.json:/app/composer.json
    working_dir: /app
    environment:
      - COMPOSER_PROCESS_TIMEOUT=2000
    command: install

  metabase-staging:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 4202:3000
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=${DB_NAME}
      - MB_DB_PORT=3306
      - MB_DB_USER=${DB_USERNAME}
      - MB_DB_PASS=${DB_PASSWORD}
      - MB_DB_HOST=db-staging
    volumes:
      - db-staging:/var/lib/mariadb/data
    depends_on:
      - db-staging
    links:
      - db-staging

volumes:
  db-staging:
