name: HeartBeats Main Guard

on:
  pull_request:
    branches: [main]
    

jobs:
  Checking-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install
        
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --standard=PSR2 --colors --encoding=utf-8 app
