name: HeartBeats Smart Analysis

on:
  push:
    branches: [main]

jobs:
  Code-Analysis: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install
        
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json  --report-file=report.json --standard=PSR2 --colors --encoding=utf-8 app
        
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --standard=PSR2 --colors --encoding=utf-8 app
        

  Branch-Update:
    needs: [Code-Analysis]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps :
      - name : Commit
        run: |
          git init
          git config --global user.email "matthieu.delarue5@gmail.com"
          git config --global user.name "Matthew"
          git add .
          git commit -m "Apply PHPCS suggested fixes"
          git push origin main
