name: HeartBeats Smart Analysis

on:
  push:
    branches: [main]

jobs:
  Code-Analysis: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install
        
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json  --report-file=report.json --standard=PSR2 --colors --encoding=utf-8 app
        
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --standard=PSR2 --colors --encoding=utf-8 app
        
      - name: Push changes
        if: ${{ steps.phpcs.outcome == 'failure' }}
        run: |
          git config user.name HeartBeats Smart Analysis
          git config user.email heartbeats-app@isep.fr
          git add .
          git commit -m "HeartBeats Smart Analysis"
          git push
