name: HeartBeats Smart Analysis

on:
  push:
    branches: [main]

jobs:
  Code-Analysis: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install
        
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json  --report-file=report.json --standard=PSR2 --colors --encoding=utf-8 app
        
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --standard=PSR2 --colors --encoding=utf-8 app
        

  Branch-Update:
    needs: [Code-Analysis]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps :

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Analysis Fix"
        commit_user_name: Matthew
        commit_user_email: "matthieu.delarue5@gmail.com"
        commit_author: Matthew "matthieu.delarue5@gmail.com"

