name: PHP CodeSniffer

on:
  push:
    branches: [main]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Run phpcs
        id: phpcs
        run: ./vendor/bin/phpcs app

  phpcbf:
    needs: phpcs
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Run phpcbf
        run: ./vendor/bin/phpcbf app

  create-issue:
    needs: [phpcs, phpcbf]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install @actions/core @actions/github
      - name: Create issue if phpcbf modified files
        if: ${{ steps.phpcbf.outputs.exit_code == 0 }}
        uses: peter-evans/create-issue-from-file@v4.0.1
        with:
          title: 'PHPCBF applied modifications to files'
          content-filepath: app
          labels: 'PHPCBF'
          assignees: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
