name: PHP CodeSniffer

on:
  push:
    branches: [main]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --standard=PSR2 --colors --encoding=utf-8 --ignore=*/vendor/* --ignore=*/tests/* --ignore=*/public/* --ignore=*/storage/* --ignore=*/database/* app

  phpcbf:
    needs: phpcs
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2.24.0
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Preview fixes
        run: ./vendor/bin/phpcbf --dry-run --standard=PSR2 --colors --encoding=utf-8 --ignore=*/vendor/* --ignore=*/tests/* --ignore=*/public/* --ignore=*/storage/* --ignore=*/database/* app
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --standard=PSR2 --colors --encoding=utf-8 --ignore=*/vendor/* --ignore=*/tests/* --ignore=*/public/* --ignore=*/storage/* --ignore=*/database/* app

  create-issue:
    needs: [phpcs, phpcbf]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install @actions/core @actions/github
      - name: Create issue if phpcbf modified files
        if: ${{ steps.phpcbf.outputs.exit-code == 0 }}
        run: |
          COUNT=$(git diff --name-only --diff-filter=M | wc -l)
          ISSUE_BODY="PHPCBF applied modifications to ${COUNT} files: \n\n"
          FILES=$(git diff --name-only --diff-filter=M)
          for FILE in $FILES; do
            ISSUE_BODY+="$(echo -e "#### ${FILE}\n\n\`\`\`diff\n$(git diff --unified=0 ${FILE} | tail -n +5)\n\`\`\`\n\n")"
          done
          echo "$ISSUE_BODY" | tee /tmp/issue-body.txt
          ISSUE_TITLE="PHPCBF applied modifications to ${COUNT} files"
          ISSUE_LABELS="PHPCBF"
          ISSUE_ASSIGNEES="${{ github.actor }}"
          ISSUE_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          node /app/create-issue.js "$ISSUE_TITLE" /tmp/issue-body.txt "$ISSUE_LABELS" "$ISSUE_ASSIGNEES" "$ISSUE_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
