name: PHP CodeSniffer

on:
  push:
    branches: [main]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json --standard=PSR2 --colors --encoding=utf-8 app
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json

  phpcbf:
    needs: phpcs
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Preview fixes
        run: ./vendor/bin/phpcbf --dry-run --standard=PSR2 --colors --encoding=utf-8 --ignore=*/vendor/* --ignore=*/tests/* --ignore=*/public/* --ignore=*/storage/* --ignore=*/database/* app
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --report=json --standard=PSR2 --colors --encoding=utf-8 --ignore=*/vendor/* --ignore=*/tests/* --ignore=*/public/* --ignore=*/storage/* --ignore=*/database/* app

  create-issue:
    needs: [phpcs, phpcbf]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install @actions/core @actions/github
        
      - name: Create Issue From analysis result
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Analysis result
          content-filepath: report.json
          labels: |
            report
            automated issue
